### ISSUE TITLE
You don't have permission to perform this action.

### ISSUE THREAD

**Issue by detruxdeveloper** [pluginsGLPI/itilcategorygroups#30]
Hello,

When I try to add a new Itil Category Groups, it says "You do not have permission to perform this action."

I'm using 9.4.1.1. with ubuntu and I also tried using 9.4 with Debian.

I checked the permission of the "Super-Admin" profile and everything is selected, and I also checked the permissions of the folder on the server itself and it is also complete.

What could it be?

**Comment by Cramoxis** [comment]
I have the same issue, it seems that the object PluginItilcategorygroupsCategory or the session doesn't have the right to create but do have the right tu update and view

**Comment by Cramoxis** [comment]
if you resolve this issue please tell me how you did resolved the problem, I will look at that issue myself and help you if I do find a solution.

**Comment by cedric-anne** [comment]
Hi,

#32 should fix your problem.

Regards
