### ISSUE TITLE
Can't select any group or user

### ISSUE THREAD

**Issue by Lokydoki** [pluginsGLPI/itilcategorygroups#8]
Hi, 
Might be doing something wrong but I am unable to select any group or user when trying to link a category and a group. I have groups and category in the same entity

glpi version : 9.1.1
plugin version : 0.90+1.0.4

![image](https://cloud.githubusercontent.com/assets/22624975/21364462/0e7e47c4-c695-11e6-93c1-af3c2e19aaac.png)

**Comment by orthagh** [comment]
Hello @Lokydoki 

You need to affect to your groups a level.
See Administration > Groups menu, select masively your needed group and click action -> update for affect a level.

Ex:

![image](https://cloud.githubusercontent.com/assets/418844/23544009/4341c226-fff5-11e6-9da7-599bc38eebd7.png)


After this action, you'll see the groups into the dropdowns
